title: Neelesh Gupta 
logo: http://neeleshg23.github.io/headshot.jpeg
description: "Email: neeleshg [at] usc [dot] edu<br><br><a href='https://www.linkedin.com/in/neelesh-gupta23'>View My LinkedIn Profile</a>"
google_analytics:
theme: jekyll-theme-minimal
linkedin_username: "neelesh-gupta23"
