title: Neelesh Gupta 
logo: http://neeleshg23.github.io/headshot.png
description: "Email: neeleshg [at] usc [dot] edu<br><br><a href='https://www.linkedin.com/in/neelesh-gupta23'>View My LinkedIn Profile</a><br><br><a href='https://scholar.google.com/citations?view_op=list_works&hl=en&user=05cnSvAAAAAJ'>View My Google Scholar</a>"
google_analytics:
theme: jekyll-theme-minimal
linkedin_username: "neelesh-gupta23"
